import { BigQuery } from "@google-cloud/bigquery";
import { env } from "@/lib/env";
import { googleAuthClient } from "@/lib/integrations/google/auth";

const TABLE = "`bigquery-public-data.google_ads_transparency_center.creative_stats`";
export type GoogleAdvertiser = { advertiserId: string; disclosedName: string | null; legalName: string | null; location: string | null };
export type GoogleCreative = GoogleAdvertiser & { creativeId: string; creativePageUrl: string | null; format: string | null; topic: string | null; regionCode: string; firstShown: Date | null; lastShown: Date | null; reachLower: number | null; reachUpper: number | null };

function client() { if (!env.GCP_PROJECT_ID) throw new Error("Google integration is unavailable: configure Vercel OIDC and Google Workload Identity Federation."); return new BigQuery({ projectId: env.GCP_PROJECT_ID, authClient: googleAuthClient() }); }
export async function testGoogleConnection() { const [rows] = await client().query({ query: "SELECT 1 AS ok", useLegacySql: false }); return rows[0]?.ok === 1; }
export async function findAdvertisers(query: string): Promise<GoogleAdvertiser[]> { const [rows] = await client().query({ query: `SELECT CAST(advertiser_id AS STRING) AS advertiser_id, ANY_VALUE(advertiser_disclosed_name) AS advertiser_disclosed_name, ANY_VALUE(advertiser_legal_name) AS advertiser_legal_name, ANY_VALUE(advertiser_location) AS advertiser_location FROM ${TABLE} WHERE LOWER(advertiser_disclosed_name) LIKE CONCAT('%', LOWER(@query), '%') OR LOWER(advertiser_legal_name) LIKE CONCAT('%', LOWER(@query), '%') GROUP BY advertiser_id LIMIT @limit`, params: { query, limit: 25 }, types: { query: "STRING", limit: "INT64" }, useLegacySql: false }); return rows.map((row: Record<string, unknown>) => ({ advertiserId: String(row.advertiser_id), disclosedName: row.advertiser_disclosed_name ? String(row.advertiser_disclosed_name) : null, legalName: row.advertiser_legal_name ? String(row.advertiser_legal_name) : null, location: row.advertiser_location ? String(row.advertiser_location) : null })); }
export async function fetchCreatives(advertiserId: string, countryCode: string, startDate: string, endDate: string): Promise<GoogleCreative[]> { const [rows] = await client().query({ query: `SELECT CAST(advertiser_id AS STRING) AS advertiser_id, advertiser_disclosed_name, advertiser_legal_name, creative_id, creative_page_url, ad_format_type, advertiser_location, topic, region.region_code, region.first_shown, region.last_shown, region.times_shown_lower_bound, region.times_shown_upper_bound FROM ${TABLE}, UNNEST(region_stats) AS region WHERE CAST(advertiser_id AS STRING) = @advertiserId AND region.region_code = @countryCode AND DATE(region.first_shown) <= DATE(@endDate) AND DATE(region.last_shown) >= DATE(@startDate) LIMIT @limit`, params: { advertiserId, countryCode, startDate, endDate, limit: 500 }, types: { advertiserId: "STRING", countryCode: "STRING", startDate: "STRING", endDate: "STRING", limit: "INT64" }, useLegacySql: false }); return rows.map((row: Record<string, unknown>) => ({ advertiserId: String(row.advertiser_id), disclosedName: row.advertiser_disclosed_name ? String(row.advertiser_disclosed_name) : null, legalName: row.advertiser_legal_name ? String(row.advertiser_legal_name) : null, location: row.advertiser_location ? String(row.advertiser_location) : null, creativeId: String(row.creative_id), creativePageUrl: row.creative_page_url ? String(row.creative_page_url) : null, format: row.ad_format_type ? String(row.ad_format_type) : null, topic: row.topic ? String(row.topic) : null, regionCode: String(row.region_code), firstShown: row.first_shown ? new Date(String(row.first_shown)) : null, lastShown: row.last_shown ? new Date(String(row.last_shown)) : null, reachLower: row.times_shown_lower_bound === null || row.times_shown_lower_bound === undefined ? null : Number(row.times_shown_lower_bound), reachUpper: row.times_shown_upper_bound === null || row.times_shown_upper_bound === undefined ? null : Number(row.times_shown_upper_bound) })); }
