const API_LIMIT = 500;
export type MetaAd = { id: string; pageId: string | null; pageName: string | null; headline: string | null; body: string | null; platform: string | null; firstShown: Date | null; lastShown: Date | null; snapshotUrl: string | null; reachLower: number | null; reachUpper: number | null; languages: string[] };
type GraphResponse = { data?: Record<string, unknown>[]; paging?: { next?: string }; error?: { message?: string; type?: string; code?: number; error_subcode?: number } };

function config() { const token = process.env.META_ACCESS_TOKEN, version = process.env.META_GRAPH_API_VERSION; if (!token || !version) throw new Error("Meta API not configured. Manual evidence upload is still available."); return { token, version }; }
async function graph(url: URL) { const response = await fetch(url, { cache: "no-store" }); const payload = await response.json() as GraphResponse; if (!response.ok || payload.error) { const error = payload.error; throw new Error(`Meta API error${error?.code ? ` ${error.code}` : ""}${error?.type ? ` (${error.type})` : ""}: ${error?.message ?? "Request failed."}`); } return payload; }
function strings(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && Boolean(item.trim())) : []; }
function first(value: unknown) { return strings(value)[0] ?? null; }
function date(value: unknown) { return typeof value === "string" && value ? new Date(value) : null; }
function reach(value: unknown) { if (!value || typeof value !== "object") return { lower: null, upper: null }; const item = value as Record<string, unknown>; return { lower: typeof item.lower_bound === "number" ? item.lower_bound : null, upper: typeof item.upper_bound === "number" ? item.upper_bound : null }; }
function mapAd(row: Record<string, unknown>): MetaAd { const bodyParts = [...strings(row.ad_creative_bodies), ...strings(row.ad_creative_link_descriptions), ...strings(row.ad_creative_link_captions)]; const euReach = reach(row.eu_total_reach); return { id: String(row.id), pageId: typeof row.page_id === "string" ? row.page_id : null, pageName: typeof row.page_name === "string" ? row.page_name : null, headline: first(row.ad_creative_link_titles), body: bodyParts.length ? [...new Set(bodyParts)].join("\n") : null, platform: strings(row.publisher_platforms).join(", ") || null, firstShown: date(row.ad_delivery_start_time), lastShown: date(row.ad_delivery_stop_time), snapshotUrl: typeof row.ad_snapshot_url === "string" ? row.ad_snapshot_url : null, reachLower: euReach.lower, reachUpper: euReach.upper, languages: strings(row.languages) }; }
function requestUrl(pageId?: string, countryCode = "HR", startDate?: string, endDate?: string) { const { token, version } = config(); const url = new URL(`https://graph.facebook.com/${version}/ads_archive`); url.searchParams.set("access_token", token); url.searchParams.set("ad_type", "ALL"); url.searchParams.set("ad_reached_countries", JSON.stringify([countryCode])); url.searchParams.set("ad_active_status", "ALL"); url.searchParams.set("fields", "id,page_id,page_name,ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,ad_snapshot_url,publisher_platforms,languages,eu_total_reach"); url.searchParams.set("limit", "100"); if (pageId) url.searchParams.set("search_page_ids", JSON.stringify([pageId])); if (startDate) url.searchParams.set("ad_delivery_date_min", startDate); if (endDate) url.searchParams.set("ad_delivery_date_max", endDate); return url; }
export async function testMetaConnection() { await graph(requestUrl()); return true; }
export async function fetchMetaAds(pageId: string, countryCode: string, startDate: string, endDate: string) { let url: URL | null = requestUrl(pageId, countryCode, startDate, endDate), result: MetaAd[] = []; while (url && result.length < API_LIMIT) { const page = await graph(url); result = result.concat((page.data ?? []).map(mapAd)).slice(0, API_LIMIT); url = page.paging?.next ? new URL(page.paging.next) : null; } return result; }
