import OpenAI from "openai";
import sharp from "sharp";
import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { analysisJsonSchema, analysisSchema } from "@/lib/analysis";
import { getCroppedImageBuffer } from "@/lib/uploads";

export const runtime = "nodejs";
const selected = { OR: [{ selectedForSlide: true }, { selectedForAnalysisEvidence: true }] };
type InputEvidence = { id: string; source: "GOOGLE" | "META"; headline: string | null; body: string | null; platform: string | null; firstShown: Date | null; lastShown: Date | null; localImagePath: string | null; cropX: number | null; cropY: number | null; cropWidth: number | null; cropHeight: number | null };
const date = (value: Date | null) => value ? value.toISOString().slice(0, 10) : "not recorded";
async function imagePart(item: InputEvidence) { if (!item.localImagePath) return null; try { const crop = item.cropX !== null && item.cropY !== null && item.cropWidth !== null && item.cropHeight !== null ? { cropX: item.cropX, cropY: item.cropY, cropWidth: item.cropWidth, cropHeight: item.cropHeight } : null; const buffer = await getCroppedImageBuffer(item.localImagePath, crop); const meta = await sharp(buffer).metadata(); return { type: "input_image" as const, image_url: `data:image/${meta.format === "jpeg" ? "jpeg" : meta.format ?? "png"};base64,${buffer.toString("base64")}`, detail: "high" as const }; } catch { return null; } }
function labels(items: InputEvidence[]) { const map = new Map<string, string>(); let google = 0, meta = 0; for (const item of items) map.set(item.id, item.source === "GOOGLE" ? `G${++google}` : `M${++meta}`); return map; }
function evidenceText(items: InputEvidence[], map: Map<string, string>, previous = false) { return items.map(item => `${previous ? "PREVIOUS " : ""}${map.get(item.id)} | ${item.source} | headline: ${item.headline ?? "—"} | body: ${item.body ?? "—"} | platform: ${item.platform ?? "—"} | first shown: ${date(item.firstShown)} | last shown: ${date(item.lastShown)}`).join("\n"); }

export async function POST(_request: NextRequest, { params }: { params: Promise<{ brandReportId: string }> }) {
  if (!process.env.OPENAI_API_KEY) return Response.json({ error: "Analysis is unavailable: OPENAI_API_KEY is not configured." }, { status: 503 });
  const { brandReportId } = await params;
  const current = await prisma.brandReport.findUnique({ where: { id: brandReportId }, include: { brand: true, report: true, adEvidence: { where: selected, orderBy: [{ source: "asc" }, { sortOrder: "asc" }, { createdAt: "asc" }] } } });
  if (!current) return Response.json({ error: "Brand report not found." }, { status: 404 });
  if (!current.adEvidence.length) return Response.json({ error: "Select at least one evidence item for a slide or analysis before generating analysis." }, { status: 400 });
  const prior = await prisma.brandReport.findFirst({ where: { brandId: current.brandId, report: { OR: [{ year: { lt: current.report.year } }, { year: current.report.year, month: { lt: current.report.month } }] } }, orderBy: [{ report: { year: "desc" } }, { report: { month: "desc" } }], include: { report: true, adEvidence: { where: selected, orderBy: [{ source: "asc" }, { sortOrder: "asc" }, { createdAt: "asc" }] } } });
  const currentEvidence = current.adEvidence as InputEvidence[], currentLabels = labels(currentEvidence), priorEvidence = prior?.adEvidence as InputEvidence[] | undefined, priorLabels = labels(priorEvidence ?? []);
  const instructions = `You analyse only supplied competitor-advertising evidence for ${current.brand.name}. Never make factual claims unless supported by supplied evidence. Every non-empty finding must cite one or more CURRENT evidence labels exactly as G1, M1, etc. Never infer spend, sales, ROI, reach, performance, or campaign success. Keep claims concise. If no prior report is supplied, changesVsPreviousMonth MUST be []. If a prior report is supplied, compare current with prior evidence and explicitly classify relevant observations as NEW, CONTINUING, or NO LONGER OBSERVED; do not cite prior labels in output, only current G/M labels. Return no unsupported sections; use empty arrays where evidence does not support a finding.`;
  const content: Array<{ type: "input_text"; text: string } | { type: "input_image"; image_url: string; detail: "high" }> = [{ type: "input_text", text: `${instructions}\n\nCURRENT REPORT: ${current.report.month}/${current.report.year}\nCURRENT EVIDENCE:\n${evidenceText(currentEvidence, currentLabels)}${prior ? `\n\nPREVIOUS REPORT: ${prior.report.month}/${prior.report.year}\nPREVIOUS EVIDENCE (comparison context only):\n${evidenceText(priorEvidence ?? [], priorLabels, true)}` : ""}` }];
  for (const item of currentEvidence) { content.push({ type: "input_text", text: `Current screenshot for ${currentLabels.get(item.id)}:` }); const part = await imagePart(item); if (part) content.push(part); }
  if (priorEvidence?.length) for (const item of priorEvidence) { content.push({ type: "input_text", text: `Previous screenshot for ${priorLabels.get(item.id)} (comparison only):` }); const part = await imagePart(item); if (part) content.push(part); }
  try { const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY }); const response = await client.responses.create({ model: process.env.OPENAI_MODEL || "gpt-5.4-mini", store: false, input: [{ role: "user", content }], text: { format: { type: "json_schema", name: "brand_advertising_analysis", strict: true, schema: analysisJsonSchema } } }); const parsed = analysisSchema.parse(JSON.parse(response.output_text)); const validLabels = new Set(currentLabels.values()); for (const item of [...parsed.keyThemes, ...parsed.modelsPromoted, ...parsed.offers, ...parsed.googleFindings, ...parsed.socialFindings, ...parsed.changesVsPreviousMonth, parsed.conclusion]) if (item.evidence.some(ref => !validLabels.has(ref))) return Response.json({ error: "The generated analysis cited invalid evidence identifiers. Please regenerate." }, { status: 502 }); await prisma.brandReport.update({ where: { id: brandReportId }, data: { analysisJson: JSON.stringify(parsed) } }); return Response.json(parsed); } catch (error) { return Response.json({ error: error instanceof Error ? `Analysis could not be generated: ${error.message}` : "Analysis could not be generated." }, { status: 502 }); }
}
