"use server";
import { AdSource } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { deleteLocalUpload, saveEvidenceBufferDetails, saveEvidenceImageDetails } from "@/lib/uploads";
import { fetchCreatives } from "@/lib/google-ads-transparency";
import { fetchMetaAds } from "@/lib/meta-ad-library";
import { capturePublicPage } from "@/lib/automatic-capture";
import { deliveryOverlapsAnalysisPeriod, isoReportDate } from "@/lib/report-period";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { MAX_REPRESENTATIVE_MEDIA_PER_SOURCE } from "@/lib/storage-policy";

type Result = { error?: string };
const nullable = (value: FormDataEntryValue | null | undefined) => typeof value === "string" && value.trim() ? value.trim() : null;
const evidenceSchema = z.object({ headline: z.string().max(500).optional(), body: z.string().max(5000).optional(), sourceUrl: z.string().url().optional().or(z.literal("")), platform: z.string().max(100).optional(), format: z.string().max(100).optional(), firstShown: z.string().optional(), lastShown: z.string().optional(), notes: z.string().max(5000).optional() });
const sourceFor = (tab: string) => tab === "google" ? AdSource.GOOGLE : AdSource.META;
const pathFor = (reportId: string, brandReportId: string) => `/reports/${reportId}/brands/${brandReportId}`;
function refresh(reportId: string, brandReportId: string) { revalidatePath(pathFor(reportId, brandReportId)); revalidatePath(`/reports/${reportId}`); }
async function ensureStorageSlot(brandReportId: string, source: AdSource, evidenceId?: string) {
  const stored = await prisma.adEvidence.count({
    where: { brandReportId, source, localImagePath: { not: null }, ...(evidenceId ? { id: { not: evidenceId } } : {}) },
  });
  if (stored >= MAX_REPRESENTATIVE_MEDIA_PER_SOURCE) throw new Error(`A maximum of ${MAX_REPRESENTATIVE_MEDIA_PER_SOURCE} stored ${source === "GOOGLE" ? "Google" : "Meta"} images is allowed per brand report.`);
}

export async function addEvidence(reportId: string, brandId: string, brandReportId: string, tab: "google" | "social", formData: FormData): Promise<Result> {
  const uploaded: Array<{ path: string; byteSize: number }> = [];
  let recordsCreated = false;
  try {
    const input = evidenceSchema.parse(Object.fromEntries([...formData].filter(([, value]) => typeof value === "string")));
    const files = formData.getAll("images").filter((item): item is File => item instanceof File && item.size > 0);
    if (!files.length) return { error: "Choose one or more JPG, PNG, or WEBP images." };
    const source = sourceFor(tab), storageSource = tab === "google" ? "google" : "meta";
    const storedCount = await prisma.adEvidence.count({ where: { brandReportId, source, localImagePath: { not: null } } });
    if (storedCount + files.length > MAX_REPRESENTATIVE_MEDIA_PER_SOURCE) return { error: `Only ${MAX_REPRESENTATIVE_MEDIA_PER_SOURCE - storedCount} more image(s) can be stored for this source.` };
    const sortOrder = await prisma.adEvidence.count({ where: { brandReportId, source } });
    const dates = { firstShown: input.firstShown ? new Date(`${input.firstShown}T00:00:00`) : null, lastShown: input.lastShown ? new Date(`${input.lastShown}T00:00:00`) : null };
    const brandReport = await prisma.brandReport.findFirst({ where: { id: brandReportId, reportId, brandId }, include: { report: { select: { id: true } } } });
    if (!brandReport) return { error: "Brand report was not found." };
    for (const file of files) uploaded.push(await saveEvidenceImageDetails(file, brandReport.report, brandId, storageSource));
    const created = await prisma.adEvidence.createMany({ data: uploaded.map((item, index) => ({ brandReportId, source, localImagePath: item.path, storedMediaBytes: item.byteSize, captureStatus: "READY", headline: nullable(input.headline), body: nullable(input.body), sourceUrl: nullable(input.sourceUrl), platform: nullable(input.platform), format: nullable(input.format), notes: nullable(input.notes), ...dates, sortOrder: sortOrder + index })) });
    if (created.count !== uploaded.length) throw new Error("Not all uploaded screenshots were saved as evidence records.");
    recordsCreated = true;
    refresh(reportId, brandReportId); return {};
  } catch (error) {
    if (!recordsCreated) await Promise.allSettled(uploaded.map(item => deleteLocalUpload(item.path)));
    return { error: error instanceof Error ? error.message : "Unable to add evidence." };
  }
}

export async function updateEvidence(reportId: string, brandReportId: string, evidenceId: string, formData: FormData): Promise<Result> {
  try { const input = evidenceSchema.parse(Object.fromEntries(formData)); const updated = await prisma.adEvidence.updateMany({ where: { id: evidenceId, brandReportId }, data: { headline: nullable(input.headline), body: nullable(input.body), sourceUrl: nullable(input.sourceUrl), platform: nullable(input.platform), format: nullable(input.format), notes: nullable(input.notes), firstShown: input.firstShown ? new Date(`${input.firstShown}T00:00:00`) : null, lastShown: input.lastShown ? new Date(`${input.lastShown}T00:00:00`) : null } }); if (!updated.count) return { error: "Evidence was not found." }; refresh(reportId, brandReportId); return {}; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to update evidence." }; }
}

export async function deleteEvidence(reportId: string, brandReportId: string, evidenceId: string): Promise<Result> { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId }, include: { media: true } }); if (!evidence) return { error: "Evidence was not found." }; const paths = [...new Set([evidence.localImagePath, ...evidence.media.map(media => media.storagePath)].filter((path): path is string => Boolean(path)))]; await prisma.adEvidence.delete({ where: { id: evidenceId } }); await Promise.allSettled(paths.map(deleteLocalUpload)); refresh(reportId, brandReportId); return {}; }
export async function setSlideSelection(reportId: string, _brandId: string, brandReportId: string, evidenceId: string, selected: boolean): Promise<Result> { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId } }); if (!evidence) return { error: "Evidence was not found." }; if (selected && !evidence.localImagePath) return { error: "Add a screenshot before selecting this evidence for a slide." }; if (selected) { const selectedCount = await prisma.adEvidence.count({ where: { brandReportId, source: evidence.source, selectedForSlide: true } }); if (selectedCount >= 8 && !evidence.selectedForSlide) return { error: "A maximum of 8 evidence images can be included on this slide." }; } await prisma.adEvidence.update({ where: { id: evidenceId }, data: { selectedForSlide: selected, ...(!selected ? { selectedForAnalysisEvidence: false } : {}) } }); refresh(reportId, brandReportId); return {}; }
export async function setAnalysisSelection(reportId: string, brandReportId: string, evidenceId: string, selected: boolean): Promise<Result> {
  const result = await prisma.$transaction(async tx => {
    const evidence = await tx.adEvidence.findFirst({ where: { id: evidenceId, brandReportId } });
    if (!evidence) return { error: "Evidence was not found." };
    if (selected && !evidence.localImagePath) return { error: "Add a screenshot before selecting this evidence for analysis." };
    if (selected && !evidence.selectedForSlide) return { error: "Include this evidence on its source slide before using it for analysis." };
    if (selected && !evidence.selectedForAnalysisEvidence) {
      const selectedCount = await tx.adEvidence.count({ where: { brandReportId, selectedForAnalysisEvidence: true } });
      if (selectedCount >= 3) return { error: "A maximum of 3 evidence images can be selected for analysis." };
    }
    await tx.adEvidence.update({ where: { id: evidenceId }, data: { selectedForAnalysisEvidence: selected } });
    return {};
  });
  refresh(reportId, brandReportId);
  return result;
}
export async function setAllSlideSelections(reportId: string, _brandId: string, brandReportId: string, tab: "google" | "social", selected: boolean): Promise<Result> { const source = sourceFor(tab); if (selected) { const evidence = await prisma.adEvidence.findMany({ where: { brandReportId, source, localImagePath: { not: null } }, orderBy: { sortOrder: "asc" }, select: { id: true } }); await prisma.$transaction([prisma.adEvidence.updateMany({ where: { brandReportId, source }, data: { selectedForSlide: false, selectedForAnalysisEvidence: false } }), prisma.adEvidence.updateMany({ where: { id: { in: evidence.slice(0, 8).map(e => e.id) } }, data: { selectedForSlide: true } })]); refresh(reportId, brandReportId); return evidence.length > 8 ? { error: "Only the first 8 items were selected; a slide can contain at most 8 images." } : {}; } await prisma.adEvidence.updateMany({ where: { brandReportId, source }, data: { selectedForSlide: false, selectedForAnalysisEvidence: false } }); refresh(reportId, brandReportId); return {}; }
export async function saveCrop(reportId: string, brandReportId: string, evidenceId: string, crop: { x: number; y: number; width: number; height: number }) { await prisma.adEvidence.updateMany({ where: { id: evidenceId, brandReportId }, data: { cropX: crop.x, cropY: crop.y, cropWidth: crop.width, cropHeight: crop.height } }); refresh(reportId, brandReportId); }
export async function resetCrop(reportId: string, brandReportId: string, evidenceId: string) { await prisma.adEvidence.updateMany({ where: { id: evidenceId, brandReportId }, data: { cropX: null, cropY: null, cropWidth: null, cropHeight: null } }); refresh(reportId, brandReportId); }
export async function moveEvidence(reportId: string, _brandId: string, brandReportId: string, evidenceId: string, direction: "previous" | "next") { const current = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId } }); if (!current) return; const items = await prisma.adEvidence.findMany({ where: { brandReportId, source: current.source }, orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }] }); const index = items.findIndex(item => item.id === evidenceId), swapIndex = direction === "previous" ? index - 1 : index + 1; if (swapIndex < 0 || swapIndex >= items.length) return; await prisma.$transaction([prisma.adEvidence.update({ where: { id: current.id }, data: { sortOrder: items[swapIndex].sortOrder } }), prisma.adEvidence.update({ where: { id: items[swapIndex].id }, data: { sortOrder: current.sortOrder } })]); refresh(reportId, brandReportId); }
export async function fetchGoogleAds(reportId: string, brandId: string, brandReportId: string): Promise<Result & { fetched?: number }> { try { const brandReport = await prisma.brandReport.findFirst({ where: { id: brandReportId, reportId, brandId }, include: { brand: { include: { googleAdvertisers: true } }, report: true } }); if (!brandReport) return { error: "Brand report was not found." }; const advertiserIds = brandReport.brand.googleAdvertisers.map(item => item.advertiserId); if (!advertiserIds.length) return { error: "Advertiser IDs not configured" }; const startDate = isoReportDate(brandReport.report.startDate), endDate = isoReportDate(brandReport.report.endDate); const records = (await fetchCreatives(advertiserIds, brandReport.report.countryCode, startDate, endDate)).filter(item => deliveryOverlapsAnalysisPeriod(item.firstShown, item.lastShown, startDate, endDate)); const count = await prisma.adEvidence.count({ where: { brandReportId, source: AdSource.GOOGLE } }); for (const [index, item] of records.entries()) await prisma.adEvidence.upsert({ where: { brandReportId_source_externalId: { brandReportId, source: AdSource.GOOGLE, externalId: item.creativeId } }, create: { brandReportId, source: AdSource.GOOGLE, externalId: item.creativeId, sourceUrl: item.creativePageUrl, snapshotUrl: item.creativePageUrl, headline: item.topic, platform: "Google Ads", format: item.format, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper, sortOrder: count + index }, update: { sourceUrl: item.creativePageUrl, snapshotUrl: item.creativePageUrl, headline: item.topic, platform: "Google Ads", format: item.format, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper } }); refresh(reportId, brandReportId); return { fetched: records.length }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to fetch Google Ads." }; } }
export async function attachGoogleScreenshot(reportId: string, brandId: string, brandReportId: string, evidenceId: string, formData: FormData): Promise<Result> { try { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId, source: AdSource.GOOGLE } }); if (!evidence) return { error: "Google creative was not found." }; const file = formData.get("screenshot"); if (!(file instanceof File) || file.size === 0) return { error: "Choose a screenshot image first." }; await ensureStorageSlot(brandReportId, AdSource.GOOGLE, evidenceId); const report = await prisma.report.findUniqueOrThrow({ where: { id: reportId }, select: { id: true } }); const stored = await saveEvidenceImageDetails(file, report, brandId, "google"); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { localImagePath: stored.path, storedMediaBytes: stored.byteSize, captureStatus: "READY", captureError: null } }); if (evidence.localImagePath && evidence.localImagePath !== stored.path) await deleteLocalUpload(evidence.localImagePath); refresh(reportId, brandReportId); return {}; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to attach screenshot." }; } }
export async function fetchMetaAdsForReport(reportId: string, brandId: string, brandReportId: string): Promise<Result & { fetched?: number }> { try { const brandReport = await prisma.brandReport.findFirst({ where: { id: brandReportId, reportId, brandId }, include: { brand: { include: { metaPages: true } }, report: true } }); if (!brandReport) return { error: "Brand report was not found." }; const pageIds = brandReport.brand.metaPages.map(item => item.pageId); if (!pageIds.length) return { error: "Meta Page IDs not configured" }; const startDate = isoReportDate(brandReport.report.startDate), endDate = isoReportDate(brandReport.report.endDate); const records = (await fetchMetaAds(pageIds, brandReport.report.countryCode, startDate, endDate)).filter(item => deliveryOverlapsAnalysisPeriod(item.firstShown, item.lastShown, startDate, endDate)); const count = await prisma.adEvidence.count({ where: { brandReportId, source: AdSource.META } }); for (const [index, item] of records.entries()) await prisma.adEvidence.upsert({ where: { brandReportId_source_externalId: { brandReportId, source: AdSource.META, externalId: item.id } }, create: { brandReportId, source: AdSource.META, externalId: item.id, sourceUrl: item.snapshotUrl, snapshotUrl: item.snapshotUrl, headline: item.headline, body: item.body, platform: item.platform, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper, notes: JSON.stringify({ importedFrom: "meta", pageName: item.pageName, pageId: item.pageId, languages: item.languages, euReach: { lower: item.reachLower, upper: item.reachUpper } }), sortOrder: count + index }, update: { sourceUrl: item.snapshotUrl, snapshotUrl: item.snapshotUrl, headline: item.headline, body: item.body, platform: item.platform, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper, notes: JSON.stringify({ importedFrom: "meta", pageName: item.pageName, pageId: item.pageId, languages: item.languages, euReach: { lower: item.reachLower, upper: item.reachUpper } }) } }); refresh(reportId, brandReportId); return { fetched: records.length }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to fetch Meta ads." }; } }
export async function attachMetaScreenshot(reportId: string, brandId: string, brandReportId: string, evidenceId: string, formData: FormData): Promise<Result> { try { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId, source: AdSource.META } }); if (!evidence) return { error: "Meta ad was not found." }; const file = formData.get("screenshot"); if (!(file instanceof File) || file.size === 0) return { error: "Choose a screenshot image first." }; await ensureStorageSlot(brandReportId, AdSource.META, evidenceId); const report = await prisma.report.findUniqueOrThrow({ where: { id: reportId }, select: { id: true } }); const stored = await saveEvidenceImageDetails(file, report, brandId, "meta"); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { localImagePath: stored.path, storedMediaBytes: stored.byteSize, captureStatus: "READY", captureError: null } }); if (evidence.localImagePath && evidence.localImagePath !== stored.path) await deleteLocalUpload(evidence.localImagePath); refresh(reportId, brandReportId); return {}; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to attach screenshot." }; } }
export async function tryAutomaticCapture(reportId: string, brandId: string, brandReportId: string, evidenceId: string): Promise<Result & { capturedEvidenceId?: string }> { try { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId } }); if (!evidence) return { error: "Evidence was not found." }; const url = evidence.snapshotUrl || evidence.sourceUrl; if (!url) return { error: "Automatic capture unavailable. Open the source and upload a screenshot manually." }; await ensureStorageSlot(brandReportId, evidence.source, evidenceId); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { captureStatus: "CAPTURING", captureError: null } }); const image = await capturePublicPage(url, evidence.source); const report = await prisma.report.findUniqueOrThrow({ where: { id: reportId }, select: { id: true } }); const stored = await saveEvidenceBufferDetails(image, report, brandId, evidence.source === AdSource.GOOGLE ? "google" : "meta"); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { localImagePath: stored.path, storedMediaBytes: stored.byteSize, captureStatus: "READY", captureError: null } }); if (evidence.localImagePath && evidence.localImagePath !== stored.path) await deleteLocalUpload(evidence.localImagePath); refresh(reportId, brandReportId); return { capturedEvidenceId: evidenceId }; } catch (error) { const message = error instanceof Error ? error.message : "Creative capture failed."; await prisma.adEvidence.updateMany({ where: { id: evidenceId, brandReportId }, data: { captureStatus: "CAPTURE_FAILED", captureError: message } }); return { error: `${message} Upload a screenshot manually if needed.` }; } }
