"use server";
import { AdSource } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { deleteLocalUpload, saveEvidenceBuffer, saveEvidenceImage } from "@/lib/uploads";
import { fetchCreatives } from "@/lib/google-ads-transparency";
import { fetchMetaAds } from "@/lib/meta-ad-library";
import { capturePublicPage } from "@/lib/automatic-capture";
import { revalidatePath } from "next/cache";
import { z } from "zod";

type Result = { error?: string };
const nullable = (value: FormDataEntryValue | null | undefined) => typeof value === "string" && value.trim() ? value.trim() : null;
const evidenceSchema = z.object({ headline: z.string().max(500).optional(), body: z.string().max(5000).optional(), sourceUrl: z.string().url().optional().or(z.literal("")), platform: z.string().max(100).optional(), format: z.string().max(100).optional(), firstShown: z.string().optional(), lastShown: z.string().optional(), notes: z.string().max(5000).optional() });
const sourceFor = (tab: string) => tab === "google" ? AdSource.GOOGLE : AdSource.META;
const pathFor = (reportId: string, brandId: string) => `/reports/${reportId}/brands/${brandId}`;
function refresh(reportId: string, brandId: string) { revalidatePath(pathFor(reportId, brandId)); revalidatePath(`/reports/${reportId}`); }

export async function addEvidence(reportId: string, brandId: string, brandReportId: string, tab: "google" | "social", formData: FormData): Promise<Result> {
  try {
    const input = evidenceSchema.parse(Object.fromEntries([...formData].filter(([, value]) => typeof value === "string")));
    const files = formData.getAll("images").filter((item): item is File => item instanceof File && item.size > 0);
    if (!files.length) return { error: "Choose one or more JPG, PNG, or WEBP images." };
    const source = sourceFor(tab), storageSource = tab === "google" ? "google" : "meta";
    const sortOrder = await prisma.adEvidence.count({ where: { brandReportId, source } });
    const dates = { firstShown: input.firstShown ? new Date(`${input.firstShown}T00:00:00`) : null, lastShown: input.lastShown ? new Date(`${input.lastShown}T00:00:00`) : null };
    const report = await prisma.report.findUniqueOrThrow({ where: { id: reportId }, select: { year: true, month: true } });
    const imagePaths = await Promise.all(files.map(file => saveEvidenceImage(file, report, brandId, storageSource)));
    await prisma.adEvidence.createMany({ data: imagePaths.map((localImagePath, index) => ({ brandReportId, source, localImagePath, headline: nullable(input.headline), body: nullable(input.body), sourceUrl: nullable(input.sourceUrl), platform: nullable(input.platform), format: nullable(input.format), notes: nullable(input.notes), ...dates, sortOrder: sortOrder + index })) });
    refresh(reportId, brandId); return {};
  } catch (error) { return { error: error instanceof Error ? error.message : "Unable to add evidence." }; }
}

export async function updateEvidence(reportId: string, brandId: string, evidenceId: string, formData: FormData): Promise<Result> {
  try { const input = evidenceSchema.parse(Object.fromEntries(formData)); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { headline: nullable(input.headline), body: nullable(input.body), sourceUrl: nullable(input.sourceUrl), platform: nullable(input.platform), format: nullable(input.format), notes: nullable(input.notes), firstShown: input.firstShown ? new Date(`${input.firstShown}T00:00:00`) : null, lastShown: input.lastShown ? new Date(`${input.lastShown}T00:00:00`) : null } }); refresh(reportId, brandId); return {}; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to update evidence." }; }
}

export async function deleteEvidence(reportId: string, brandId: string, evidenceId: string): Promise<Result> { const evidence = await prisma.adEvidence.delete({ where: { id: evidenceId } }); await deleteLocalUpload(evidence.localImagePath); refresh(reportId, brandId); return {}; }
export async function setSlideSelection(reportId: string, brandId: string, brandReportId: string, evidenceId: string, selected: boolean): Promise<Result> { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId } }); if (!evidence) return { error: "Evidence was not found." }; if (selected) { const selectedCount = await prisma.adEvidence.count({ where: { brandReportId, source: evidence.source, selectedForSlide: true } }); if (selectedCount >= 8 && !evidence.selectedForSlide) return { error: "A maximum of 8 evidence images can be included on this slide." }; } await prisma.adEvidence.update({ where: { id: evidenceId }, data: { selectedForSlide: selected } }); refresh(reportId, brandId); return {}; }
export async function setAnalysisSelection(reportId: string, brandId: string, evidenceId: string, selected: boolean) { await prisma.adEvidence.update({ where: { id: evidenceId }, data: { selectedForAnalysisEvidence: selected } }); refresh(reportId, brandId); }
export async function setAllSlideSelections(reportId: string, brandId: string, brandReportId: string, tab: "google" | "social", selected: boolean): Promise<Result> { const source = sourceFor(tab); if (selected) { const evidence = await prisma.adEvidence.findMany({ where: { brandReportId, source }, orderBy: { sortOrder: "asc" }, select: { id: true } }); await prisma.$transaction([prisma.adEvidence.updateMany({ where: { brandReportId, source }, data: { selectedForSlide: false } }), prisma.adEvidence.updateMany({ where: { id: { in: evidence.slice(0, 8).map(e => e.id) } }, data: { selectedForSlide: true } })]); refresh(reportId, brandId); return evidence.length > 8 ? { error: "Only the first 8 items were selected; a slide can contain at most 8 images." } : {}; } await prisma.adEvidence.updateMany({ where: { brandReportId, source }, data: { selectedForSlide: false } }); refresh(reportId, brandId); return {}; }
export async function saveCrop(reportId: string, brandId: string, evidenceId: string, crop: { x: number; y: number; width: number; height: number }) { await prisma.adEvidence.update({ where: { id: evidenceId }, data: { cropX: crop.x, cropY: crop.y, cropWidth: crop.width, cropHeight: crop.height } }); refresh(reportId, brandId); }
export async function resetCrop(reportId: string, brandId: string, evidenceId: string) { await prisma.adEvidence.update({ where: { id: evidenceId }, data: { cropX: null, cropY: null, cropWidth: null, cropHeight: null } }); refresh(reportId, brandId); }
export async function moveEvidence(reportId: string, brandId: string, brandReportId: string, evidenceId: string, direction: "previous" | "next") { const current = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId } }); if (!current) return; const items = await prisma.adEvidence.findMany({ where: { brandReportId, source: current.source }, orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }] }); const index = items.findIndex(item => item.id === evidenceId), swapIndex = direction === "previous" ? index - 1 : index + 1; if (swapIndex < 0 || swapIndex >= items.length) return; await prisma.$transaction([prisma.adEvidence.update({ where: { id: current.id }, data: { sortOrder: items[swapIndex].sortOrder } }), prisma.adEvidence.update({ where: { id: items[swapIndex].id }, data: { sortOrder: current.sortOrder } })]); refresh(reportId, brandId); }
export async function fetchGoogleAds(reportId: string, brandId: string, brandReportId: string): Promise<Result & { fetched?: number }> { try { const brandReport = await prisma.brandReport.findFirst({ where: { id: brandReportId, reportId, brandId }, include: { brand: true, report: true } }); if (!brandReport) return { error: "Brand report was not found." }; if (!brandReport.brand.googleAdvertiserId) return { error: "Set a Google Advertiser ID on this brand before fetching ads." }; const startDate = new Date(Date.UTC(brandReport.report.year, brandReport.report.month - 1, 1)).toISOString().slice(0, 10), endDate = new Date(Date.UTC(brandReport.report.year, brandReport.report.month, 0)).toISOString().slice(0, 10); const records = await fetchCreatives(brandReport.brand.googleAdvertiserId, brandReport.report.countryCode, startDate, endDate); const count = await prisma.adEvidence.count({ where: { brandReportId, source: AdSource.GOOGLE } }); for (const [index, item] of records.entries()) await prisma.adEvidence.upsert({ where: { brandReportId_source_externalId: { brandReportId, source: AdSource.GOOGLE, externalId: item.creativeId } }, create: { brandReportId, source: AdSource.GOOGLE, externalId: item.creativeId, sourceUrl: item.creativePageUrl, snapshotUrl: item.creativePageUrl, headline: item.topic, platform: "Google Ads", format: item.format, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper, sortOrder: count + index }, update: { sourceUrl: item.creativePageUrl, snapshotUrl: item.creativePageUrl, headline: item.topic, platform: "Google Ads", format: item.format, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper } }); refresh(reportId, brandId); return { fetched: records.length }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to fetch Google Ads." }; } }
export async function attachGoogleScreenshot(reportId: string, brandId: string, brandReportId: string, evidenceId: string, formData: FormData): Promise<Result> { try { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId, source: AdSource.GOOGLE } }); if (!evidence) return { error: "Google creative was not found." }; const file = formData.get("screenshot"); if (!(file instanceof File) || file.size === 0) return { error: "Choose a screenshot image first." }; const report = await prisma.report.findUniqueOrThrow({ where: { id: reportId }, select: { year: true, month: true } }); const localImagePath = await saveEvidenceImage(file, report, brandId, "google"); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { localImagePath } }); refresh(reportId, brandId); return {}; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to attach screenshot." }; } }
export async function fetchMetaAdsForReport(reportId: string, brandId: string, brandReportId: string): Promise<Result & { fetched?: number }> { try { const brandReport = await prisma.brandReport.findFirst({ where: { id: brandReportId, reportId, brandId }, include: { brand: true, report: true } }); if (!brandReport) return { error: "Brand report was not found." }; if (!brandReport.brand.metaPageId) return { error: "Set a Meta Page ID on this brand before fetching ads." }; const startDate = new Date(Date.UTC(brandReport.report.year, brandReport.report.month - 1, 1)).toISOString().slice(0, 10), endDate = new Date(Date.UTC(brandReport.report.year, brandReport.report.month, 0)).toISOString().slice(0, 10); const records = await fetchMetaAds(brandReport.brand.metaPageId, brandReport.report.countryCode, startDate, endDate); const count = await prisma.adEvidence.count({ where: { brandReportId, source: AdSource.META } }); for (const [index, item] of records.entries()) await prisma.adEvidence.upsert({ where: { brandReportId_source_externalId: { brandReportId, source: AdSource.META, externalId: item.id } }, create: { brandReportId, source: AdSource.META, externalId: item.id, sourceUrl: item.snapshotUrl, snapshotUrl: item.snapshotUrl, headline: item.headline, body: item.body, platform: item.platform, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper, notes: JSON.stringify({ importedFrom: "meta", pageName: item.pageName, pageId: item.pageId, languages: item.languages, euReach: { lower: item.reachLower, upper: item.reachUpper } }), sortOrder: count + index }, update: { sourceUrl: item.snapshotUrl, snapshotUrl: item.snapshotUrl, headline: item.headline, body: item.body, platform: item.platform, firstShown: item.firstShown, lastShown: item.lastShown, reachLower: item.reachLower, reachUpper: item.reachUpper, notes: JSON.stringify({ importedFrom: "meta", pageName: item.pageName, pageId: item.pageId, languages: item.languages, euReach: { lower: item.reachLower, upper: item.reachUpper } }) } }); refresh(reportId, brandId); return { fetched: records.length }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to fetch Meta ads." }; } }
export async function attachMetaScreenshot(reportId: string, brandId: string, brandReportId: string, evidenceId: string, formData: FormData): Promise<Result> { try { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId, source: AdSource.META } }); if (!evidence) return { error: "Meta ad was not found." }; const file = formData.get("screenshot"); if (!(file instanceof File) || file.size === 0) return { error: "Choose a screenshot image first." }; const report = await prisma.report.findUniqueOrThrow({ where: { id: reportId }, select: { year: true, month: true } }); const localImagePath = await saveEvidenceImage(file, report, brandId, "meta"); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { localImagePath } }); refresh(reportId, brandId); return {}; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to attach screenshot." }; } }
export async function tryAutomaticCapture(reportId: string, brandId: string, brandReportId: string, evidenceId: string): Promise<Result & { capturedEvidenceId?: string }> { try { const evidence = await prisma.adEvidence.findFirst({ where: { id: evidenceId, brandReportId } }); if (!evidence) return { error: "Evidence was not found." }; const url = evidence.snapshotUrl || evidence.sourceUrl; if (!url) return { error: "Automatic capture unavailable. Open the source and upload a screenshot manually." }; const image = await capturePublicPage(url); const report = await prisma.report.findUniqueOrThrow({ where: { id: reportId }, select: { year: true, month: true } }); const localImagePath = await saveEvidenceBuffer(image, report, brandId, evidence.source === AdSource.GOOGLE ? "google" : "meta"); await prisma.adEvidence.update({ where: { id: evidenceId }, data: { localImagePath } }); refresh(reportId, brandId); return { capturedEvidenceId: evidenceId }; } catch { return { error: "Automatic capture unavailable. Open the source and upload a screenshot manually." }; } }
