"use client";
import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";
import { emptyAnalysis, type Analysis } from "@/lib/analysis";
import { saveAnalysisEdits } from "./analysis-actions";

const sections: Array<[keyof Omit<Analysis, "conclusion">, string]> = [["keyThemes", "Key communication themes"], ["modelsPromoted", "Models/products promoted"], ["offers", "Offers / financing / pricing"], ["googleFindings", "Google advertising observations"], ["socialFindings", "Social media observations"], ["changesVsPreviousMonth", "Changes vs previous month"]];
function parse(raw: string | null) { try { return raw ? JSON.parse(raw) as Analysis : emptyAnalysis; } catch { return emptyAnalysis; } }
function FindingList({ items }: { items: Analysis["keyThemes"] }) { return items.length ? <ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-slate-700">{items.map((item, index) => <li key={`${item.text}-${index}`}>{item.text} <span className="font-semibold text-teal-700">[{item.evidence.join(", ")}]</span></li>)}</ul> : <p className="mt-2 text-sm text-slate-400">No evidence-supported findings.</p>; }
export default function AnalysisManager({ reportId, brandReportId, generatedJson, editedJson, analysisEvidenceCount }: { reportId: string; brandReportId: string; generatedJson: string | null; editedJson: string | null; analysisEvidenceCount: number }) {
  const router = useRouter(), [editing, setEditing] = useState(false), [raw, setRaw] = useState(editedJson || generatedJson || JSON.stringify(emptyAnalysis, null, 2)), [error, setError] = useState(""), [message, setMessage] = useState(""), [pending, startTransition] = useTransition(); const analysis = useMemo(() => parse(editedJson || generatedJson), [editedJson, generatedJson]);
  const generate = (regenerate: boolean) => { if (regenerate && !confirm("Regenerate the AI analysis? This replaces the generated analysis, but retains your manual edit until you save a new one.")) return; setError(""); setMessage(""); startTransition(async () => { const response = await fetch(`/api/brand-reports/${brandReportId}/generate-analysis`, { method: "POST" }); const payload = await response.json() as Analysis | { error: string }; if (!response.ok || "error" in payload) setError("error" in payload ? payload.error : "Analysis could not be generated."); else { setRaw(JSON.stringify(payload, null, 2)); setMessage("Analysis generated. Review and save edits if needed."); router.refresh(); } }); };
  const save = () => { setError(""); startTransition(async () => { try { await saveAnalysisEdits(reportId, brandReportId, raw); setEditing(false); setMessage("Manual analysis edits saved."); router.refresh(); } catch (cause) { setError(cause instanceof Error ? `Invalid analysis JSON: ${cause.message}` : "Unable to save analysis edits."); } }); };
  return <div className="space-y-5">{analysisEvidenceCount > 3 && <p className="rounded-lg bg-rose-50 p-4 text-sm font-medium text-rose-800">{analysisEvidenceCount} analysis evidence items are selected. Reduce this to 3 or fewer before exporting PowerPoint.</p>}<div className="flex flex-wrap gap-3"><button className="button" disabled={pending} onClick={() => generate(Boolean(generatedJson))}>{generatedJson ? "Regenerate Analysis" : "Generate Analysis"}</button>{(generatedJson || editedJson) && <button className="button button-secondary" onClick={() => setEditing(!editing)}>{editing ? "Cancel editing" : "Edit analysis"}</button>}</div>{error && <p className="rounded-lg bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}{message && <p className="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800">{message}</p>}{editing ? <div className="card p-5"><p className="mb-3 text-sm text-slate-500">Edit bullets, conclusion, and evidence identifiers directly. Evidence identifiers must be in the form G1 or M1.</p><textarea className="min-h-[30rem] font-mono text-xs" value={raw} onChange={event => setRaw(event.target.value)} /><div className="mt-4"><button className="button" disabled={pending} onClick={save}>Save manual edits</button></div></div> : <div className="grid gap-4 lg:grid-cols-2">{sections.map(([key, title]) => <section key={key} className="card p-5"><h2 className="font-bold">{title}</h2><FindingList items={analysis[key]}/></section>)}<section className="card p-5 lg:col-span-2"><h2 className="font-bold">Overall conclusion</h2>{analysis.conclusion.text ? <p className="mt-2 text-sm text-slate-700">{analysis.conclusion.text} <span className="font-semibold text-teal-700">[{analysis.conclusion.evidence.join(", ")}]</span></p> : <p className="mt-2 text-sm text-slate-400">Analysis has not yet been generated.</p>}</section></div>}</div>;
}
