import { NextRequest } from "next/server";
import PptxGenJS from "pptxgenjs";
import sharp from "sharp";
import { prisma } from "@/lib/prisma";
import { getCroppedImageBuffer } from "@/lib/uploads";
import { months } from "@/lib/utils";

export const runtime = "nodejs";

const W = 13.333, H = 7.5, TEAL = "102D35", ACCENT = "159B93", INK = "17222D", MUTED = "64748B", PAPER = "F7F9FA";
const RECT = "rect" as PptxGenJS.ShapeType;
type Evidence = { id: string; source: "GOOGLE" | "META"; localImagePath: string | null; cropX: number | null; cropY: number | null; cropWidth: number | null; cropHeight: number | null; sortOrder: number };

async function imageData(localImagePath: string, crop?: { cropX: number | null; cropY: number | null; cropWidth: number | null; cropHeight: number | null }) {
  const buffer = await getCroppedImageBuffer(localImagePath, crop && crop.cropX !== null && crop.cropY !== null && crop.cropWidth !== null && crop.cropHeight !== null ? { cropX: crop.cropX, cropY: crop.cropY, cropWidth: crop.cropWidth, cropHeight: crop.cropHeight } : null);
  const meta = await sharp(buffer).metadata();
  return { data: `data:image/${meta.format === "jpeg" ? "jpeg" : meta.format ?? "png"};base64,${buffer.toString("base64")}`, width: meta.width ?? 1, height: meta.height ?? 1 };
}
function contain(box: { x: number; y: number; w: number; h: number }, image: { width: number; height: number }) { const ratio = Math.min(box.w / image.width, box.h / image.height), w = image.width * ratio, h = image.height * ratio; return { x: box.x + (box.w - w) / 2, y: box.y + (box.h - h) / 2, w, h }; }
function addHeader(slide: PptxGenJS.Slide, brand: string, title: string, period: string, logoPath?: string | null) { slide.background = { color: PAPER }; slide.addShape(RECT, { x: 0, y: 0, w: W, h: 1.18, fill: { color: TEAL }, line: { color: TEAL } }); slide.addText(`${brand.toUpperCase()} | ${title} | ${period.toUpperCase()}`, { x: .48, y: .32, w: 10.8, h: .3, fontFace: "Arial", fontSize: 16, bold: true, color: "FFFFFF", margin: 0, breakLine: false, fit: "shrink" }); if (logoPath) slide.addText(brand, { x: 11.5, y: .4, w: 1.3, h: .2, color: "D9F1EF", fontFace: "Arial", fontSize: 8, align: "right", margin: 0 }); }
async function addLogo(slide: PptxGenJS.Slide, logoPath?: string | null) { if (!logoPath) return; try { const image = await imageData(logoPath); slide.addImage({ data: image.data, ...contain({ x: 11.72, y: .2, w: 1.08, h: .7 }, image) }); } catch { /* Missing logo should never block an export. */ } }
function grid(count: number) { if (count === 1) return [1, 1]; if (count === 2) return [2, 1]; if (count === 3) return [3, 1]; if (count <= 4) return [2, 2]; if (count <= 6) return [3, 2]; return [4, 2]; }
async function addEvidenceGrid(slide: PptxGenJS.Slide, evidence: Evidence[], prefix: "G" | "M", labels: Map<string, string>) { if (!evidence.length) { slide.addText("No evidence selected for this slide.", { x: .55, y: 3.35, w: 12.2, h: .3, align: "center", fontFace: "Arial", fontSize: 17, color: MUTED, margin: 0 }); return; } const [columns, rows] = grid(evidence.length), gap = .13, x = .52, y = 1.58, totalW = 12.29, totalH = 5.35, cellW = (totalW - gap * (columns - 1)) / columns, cellH = (totalH - gap * (rows - 1)) / rows; for (let index = 0; index < evidence.length; index++) { const item = evidence[index], box = { x: x + (index % columns) * (cellW + gap), y: y + Math.floor(index / columns) * (cellH + gap), w: cellW, h: cellH }; slide.addShape(RECT, { ...box, fill: { color: "E7EDF0" }, line: { color: "D5DFE3", width: .5 } }); try { if (item.localImagePath) { const image = await imageData(item.localImagePath, item); slide.addImage({ data: image.data, ...contain(box, image) }); } } catch { slide.addText("Image unavailable", { ...box, fontFace: "Arial", fontSize: 10, align: "center", valign: "middle", color: MUTED, margin: 0 }); } slide.addShape(RECT, { x: box.x + .08, y: box.y + .08, w: .32, h: .22, fill: { color: TEAL, transparency: 8 }, line: { color: TEAL } }); slide.addText(labels.get(item.id) ?? `${prefix}${index + 1}`, { x: box.x + .08, y: box.y + .105, w: .32, h: .12, fontFace: "Arial", fontSize: 7, bold: true, color: "FFFFFF", align: "center", margin: 0 }); } }
function sectionText(value: unknown): string { if (typeof value === "string") return value; if (Array.isArray(value)) return value.map(item => sectionText(item)).filter(Boolean).map(item => `• ${item}`).join("\n"); if (value && typeof value === "object") { const item = value as { text?: unknown; evidence?: unknown }; if (typeof item.text === "string") return `${item.text}${Array.isArray(item.evidence) && item.evidence.length ? ` [${item.evidence.join(", ")}]` : ""}`; return Object.values(value).map(item => sectionText(item)).filter(Boolean).join("\n"); } return ""; }
function analysisSections(raw: string | null) { if (!raw) return []; try { const data = JSON.parse(raw) as Record<string, unknown>; const items = [["Key communication themes", ["keyThemes", "keyCommunicationThemes", "themes"]], ["Models/products promoted", ["modelsPromoted", "modelsProductsPromoted", "models"]], ["Offers / financing / pricing", ["offers", "offersFinancingPricing"]], ["Google advertising observations", ["googleFindings", "googleAdvertisingObservations", "googleObservations"]], ["Social media observations", ["socialFindings", "socialMediaObservations", "socialObservations"]], ["Changes vs previous month", ["changesVsPreviousMonth", "changes"]], ["Overall conclusion", ["conclusion", "overallConclusion"]]] as const; return items.map(([title, keys]) => ({ title, value: keys.map(key => sectionText(data[key])).find(Boolean) ?? "" })).filter(item => item.value); } catch { return [{ title: "Analysis", value: raw }]; } }
async function addAnalysisSlide(pptx: PptxGenJS, brand: { name: string; logoPath: string | null }, period: string, rawAnalysis: string | null, evidence: Evidence[], labels: Map<string, string>) {
  const slide = pptx.addSlide(); addHeader(slide, brand.name, "MONTHLY ADVERTISING ANALYSIS", period, brand.logoPath); await addLogo(slide, brand.logoPath);
  const sections = analysisSections(rawAnalysis);
  if (!sections.length) slide.addText("Analysis has not yet been generated.", { x: .6, y: 1.72, w: 7.1, h: .35, fontFace: "Arial", fontSize: 18, color: MUTED, margin: 0 });
  else { let y = 1.52; for (const section of sections) { if (y > 6.7) break; slide.addText(section.title.toUpperCase(), { x: .58, y, w: 7.2, h: .16, fontFace: "Arial", fontSize: 8, bold: true, color: ACCENT, charSpacing: 1.2, margin: 0 }); y += .23; slide.addText(section.value, { x: .58, y, w: 7.05, h: Math.min(.66, .15 + section.value.length / 150), fontFace: "Arial", fontSize: 10.5, color: INK, margin: .02, fit: "shrink" }); y += Math.min(.8, .29 + section.value.length / 150); } }
  slide.addShape(RECT, { x: 8.06, y: 1.38, w: 4.7, h: 5.75, fill: { color: "EAF0F1" }, line: { color: "D5DFE3", width: .5 } }); slide.addText("SELECTED EVIDENCE", { x: 8.33, y: 1.57, w: 3.9, h: .14, fontFace: "Arial", fontSize: 8, bold: true, color: MUTED, charSpacing: 1.1, margin: 0 });
  const shown = evidence.slice(0, 3); if (!shown.length) slide.addText("No analysis evidence selected.", { x: 8.35, y: 4.1, w: 3.95, h: .25, align: "center", fontFace: "Arial", fontSize: 11, color: MUTED, margin: 0 });
  for (let index = 0; index < shown.length; index++) { const item = shown[index], box = { x: 8.33, y: 1.93 + index * 1.68, w: 3.95, h: 1.43 }; slide.addShape(RECT, { ...box, fill: { color: "D8E1E4" }, line: { color: "FFFFFF", width: 1 } }); try { if (item.localImagePath) { const image = await imageData(item.localImagePath, item); slide.addImage({ data: image.data, ...contain(box, image) }); } } catch { /* Keep the evidence placeholder. */ } const label = labels.get(item.id) ?? (item.source === "GOOGLE" ? `G${index + 1}` : `M${index + 1}`); slide.addShape(RECT, { x: box.x + .08, y: box.y + .08, w: .38, h: .23, fill: { color: TEAL }, line: { color: TEAL } }); slide.addText(label, { x: box.x + .08, y: box.y + .105, w: .38, h: .1, fontFace: "Arial", fontSize: 7, bold: true, color: "FFFFFF", align: "center", margin: 0 }); }
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const cover = request.nextUrl.searchParams.get("cover") === "1"; const report = await prisma.report.findUnique({ where: { id }, include: { brandReports: { where: { included: true }, orderBy: { brand: { sortOrder: "asc" } }, include: { brand: true, adEvidence: { orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }] } } } } }); if (!report) return new Response("Report not found.", { status: 404 }); if (report.brandReports.some(br => br.adEvidence.filter(item => item.selectedForAnalysisEvidence).length > 3)) return new Response("Reduce selected analysis evidence to a maximum of 3 per brand before exporting.", { status: 400 }); const period = `${months[report.month - 1]} ${report.year}`, pptx = new PptxGenJS(); pptx.layout = "LAYOUT_WIDE"; pptx.author = "Competitor Ads Report"; pptx.subject = `Competitor advertising report – ${period}`; pptx.title = report.title; pptx.company = "Competitor Ads Report";
  if (cover) { const slide = pptx.addSlide(); slide.background = { color: TEAL }; slide.addText("COMPETITOR ADS REPORT", { x: .68, y: 2.48, w: 11.9, h: .42, fontFace: "Arial", fontSize: 27, bold: true, color: "FFFFFF", align: "center", margin: 0 }); slide.addText(period.toUpperCase(), { x: .68, y: 3.08, w: 11.9, h: .22, fontFace: "Arial", fontSize: 13, color: "BCE5E1", align: "center", charSpacing: 2, margin: 0 }); }
  for (const br of report.brandReports) { const all = br.adEvidence as Evidence[], google = all.filter(item => item.source === "GOOGLE" && (br.adEvidence.find(e => e.id === item.id)?.selectedForSlide)), meta = all.filter(item => item.source === "META" && (br.adEvidence.find(e => e.id === item.id)?.selectedForSlide)), labels = new Map<string, string>(); all.filter(item => item.source === "GOOGLE").forEach((item, index) => labels.set(item.id, `G${index + 1}`)); all.filter(item => item.source === "META").forEach((item, index) => labels.set(item.id, `M${index + 1}`)); let slide = pptx.addSlide(); addHeader(slide, br.brand.name, "GOOGLE ADS", period, br.brand.logoPath); await addLogo(slide, br.brand.logoPath); slide.addText("SOURCE: GOOGLE ADS TRANSPARENCY CENTER", { x: .52, y: 1.3, w: 6.5, h: .14, fontFace: "Arial", fontSize: 7.5, bold: true, color: MUTED, charSpacing: .7, margin: 0 }); await addEvidenceGrid(slide, google.slice(0, 8), "G", labels); slide = pptx.addSlide(); addHeader(slide, br.brand.name, "SOCIAL MEDIA ADS", period, br.brand.logoPath); await addLogo(slide, br.brand.logoPath); slide.addText("SOURCE: META AD LIBRARY", { x: .52, y: 1.3, w: 6.5, h: .14, fontFace: "Arial", fontSize: 7.5, bold: true, color: MUTED, charSpacing: .7, margin: 0 }); await addEvidenceGrid(slide, meta.slice(0, 8), "M", labels); await addAnalysisSlide(pptx, br.brand, period, br.analysisEditedJson || br.analysisJson, all.filter(item => br.adEvidence.find(e => e.id === item.id)?.selectedForAnalysisEvidence), labels); }
  const buffer = await pptx.write({ outputType: "nodebuffer" }) as Buffer; return new Response(new Uint8Array(buffer), { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation", "Content-Disposition": `attachment; filename="Competitor-Ads-${report.year}-${String(report.month).padStart(2, "0")}.pptx"` } }); }
